### ISSUE TITLE
追踪Pango提名的China变异株

### ISSUE THREAD

**Issue by Memorablea** [Memorablea/COVID-19-#24]
- [x] FL.2 (XBB.1.9.1.2) sublineage with S:141-144del (27 seqs in China) #68 `失败`
- [x] Multiple lineages with S:N481K (updated 26/06) #59 `FL.1.6非本土 HM.1非本土`
- [x] EG.4+S:A623V in China(40 seqs, 2 countries) # 46 `EG.4.2`
- [x] FU.1 with A460G to describe tree (1246 seq.) #50 #2037 `取消提名`
- [x] Quick (in China) FR.1 Sublineage with S:P82H (46 Seqs - China, Japan) #2006 `FR.1.1`
- [x] https://github.com/cov-lineages/pango-designation/issues/2000 `FY.3.2`
- [x] XBB.1.9.1 sublineage with S:A411S emerged in China (74 seqs in China and Australia) #1996 `FL.13.1`
- [x] XBB.1.22.1 sublineage with S:K478R (6seqs in Indonesia, China and South Korea) #1965 `FY.5非本土`
- [x] FL.2 sublineage with Orf1b:K1383R circulating in China and other countries (127 seq) and then S:Q146K (35 seq) #78 #2016 `FL.2.3`
- [x] XBB.1.9.1 with s:d614a (9 seq, pakistan france china scotland) #81 `失败`
- [x] XBB.1.16.2 with S:L84I, ORF1ab:A4068S in China (88 seq) #82 #2066` GY.1`
- [x] GJ.1 sublineage with ORF1b:V1110I, C1549T, and C7819G first detected in South Korea (235 GISAID seqs as of 2023-06-26; USA, China, Singapore, China, South Korea, Australia, Italy, Japan, New Zealand, Switzerland, Finland, Hong Kong, Philippines, Spain, Sweden, UK) #2059 `GJ.1.2非本土`
- [x] FL.13 with S:K356T in China(16 seqs, +2 Hong Kong) #104 #2073 `FL.13.2`
- [x] FL.4 + N:K256R sublineage fast spreading from China (203 seqs )#117 #2087 `子分支命名FL.4.10`
- [x] FL.4 with S:D1259Y and N:T334I #140 #2074 `FL.4.11`
- [ ] FL.2.3 (XBB.1.9.1.2.3) with ORF1ab: K5784R and S: Q146K（203 seqs China, UK, USA, Japan, Australia, South Korea, Singapore, Italy, France） #2078
- [x] XBB.1.19.1 sublineage with ORF1a:D264N and N:M322V circulating in Beijing(123 seq, 7 countries) #157 `GW.1`
- [x] Potential Recombinant of FL.5 and XBB.1.9.2* with additional S:L938F in China (11 seqs) #161 `取消提名`
- [x] XBB.1.9.1 + Orf1a:L3588F (NSP6_L19F) spreading in China and multiple countries (88 seqs) Full credit to @Over-There-is and @Memorablea for exploring the chinese tree #196 `取消提名`
- [x] FL.21 sublineage with Orf1a:V1019F (NSP3_V201F), I2873M (NSP4_I110M) circulating in China(133 seq, 10 countries) #187 `FL.21.2`
- [ ] GF.1 (XBB.1.5.24.1) with ORF1b:G814D (NSP2_G634D), ORF1b:Q1546H (NSP3_G728H) (447 seqs, mainly in China, 10 countries) #191 #2086
- [x] XBB.1.34.2 sublineage with S:F456L (T22928C)(14 seqs, including a small saltation branch with S:K478R and S:E554Q) #217 `HB.1非国产`
- [x] FL.4.2 sublineage with S:V289I (77 seqs mainly in China) #250 `失败`
- [x] FL.2 +Orf8:S67F+S:G1099D in China (33 seqs, 2 countries) #248 `母分支命名FL.2.4`
- [x] #2037 + S:Q493L (8 seqs, 2 countries) #258 `失败`
- [x] GD.1 (S:Y453F) with S:F456L, definite international spread [2 seqs, USA, China] #262 `非本土 失败`
- [x] XBB.1.46 with S:T478Q and S:F486P (10 seqs, 3 countries) #272 `取消提名`
- [x] XBB.1.16 with ORF7a:T39I (284 seqs, 16 countries) #276 'XBB.1.16.18非国产'
- [x] XBB.1.16.2 with ORF1a:V1765I (nsp3_V947I) and N:T165I (68 seqs, 10 countries) with a potential subbranch with S:F456L (1) #308 `母分支命名GY.6`
- [x] EG.6.1 (S:F456L) sublineage with ORF1a:A2584V and ORF1a:T2977K first detected in Florida, USA (25 GISAID seqs as of 2023-07-01; Canada, USA, France, Austria, China) #306 `非本土 取消提名`
- [ ] XBB.1.5.59+orf1a:T1429I, S:V510I emerging in New Zealand (49 seqs, 5 countries) #304 #2152
- [x] XBB.1.5.94 +11-nuc,5-aa including S:478R (11 seqs, 6 countries) #314 #2164 `取消提名`
- [x] XBB.1.16 with Orf9b:P3S, N:P6L, S:V1264L in China (8 seqs) #313 `取消提名`
- [x] FY.3.1 (XBB.1.22.1.3.1) sublineage with S:Y266C (5 seqs in Singapore and China) #317 `失败`

**Comment by Walde1nsamkeit** [comment]
#2016

**Comment by Memorablea** [comment]
> https://github.com/cov-lineages/pango-designation/issues/2016

**Comment by Memorablea** [comment]
由@Over-There-Is 提出的Several Potential Recombinants in China  [重组](https://github.com/sars-cov-2-variants/lineage-proposals/issues/108))))

**Comment by Walde1nsamkeit** [comment]
#50?

**Comment by Memorablea** [comment]
感谢你一直以来的工作！
